// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptewkumscpzmucdkhqjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0ZXdrdW1zY3B6bXVjZGtocWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NTcxNTEsImV4cCI6MjA5MjUzMzE1MX0.igm9nIFKrlqf8-_YsDhEjviHrKs098eGtGLi3RCN7Vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});